spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/controla-crm
    username: postgres
    password: 135790sql86421

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080