spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/controla-crm
    username: postgres
    password: 135790sql86421

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false


server:
  port: 8080

jwt:
  secret: "FNKDdSnAUGYv98FNuAge0kGSZ9xG4otqjMch7d7HVcp"
  access-expiration-ms: 900000
  refresh-expiration-ms: 604800000

file:
  upload:
    dir: ./uploads

