spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

file:
  upload:
    dir: ${UPLOAD_DIR}